### ISSUE TITLE
Release - Todo list

### ISSUE THREAD

**Issue by dfinke** [dfinke/PSAI#82]
# On or about Jan 6, 2025
## v0.5.0 release check list
- [ ] Review current tests and functions for completeness
- [ ] Comment based help for all functions
- [ ] Unit tests for params for functions - including counts of parms, order of params, attributes of params. Going forward, this can catch which ones we change that may cause issues.
- [ ] `Get-AIKeyInfo` needs tests to ensure order etc

## Next features

- [ ] Provider feature checklist - each provider must inform PSAI what features it supports, ie. tool calling, Assistants, etc. That would make it possible to stop things that would not work anyway gracefully. It would also enable us to add basic features for providers fast and then expand on them at a more controllable pace.
- [ ] Move ToolCalls to Invoke-OAIChatCompletion.
- [ ] Tab completion for Provider and Model. This is tricky. We can add cmdlets to the current implementation, knowing that it is not perfect and then figure out how to handle the "must be known at compute time" issue.
